# Generated by Django 3.2.8 on 2023-04-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaria',
            name='nome_completo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
