# Generated by Django 3.2.8 on 2023-04-26 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_diaria_nome_completo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaria',
            old_name='nome_completo',
            new_name='nome_servico',
        ),
    ]
